import os

IP_INCREMENT = 10000000
TIME_INCREMENT = 15
IPV4_INT_START = 1
IPV4_INT_STOP = 4294967295
BASE_DIR = os.getcwd()
MASSCAN_BIN = BASE_DIR + '/Scanners/src/masscan/bin/masscan'
MASSCAN_CMD = '-c ./xerxes-masscan.conf -p {} -oX {} --pcap {} {}-{}'
XML_OUT = BASE_DIR + '/OutFiles/xerxes-masscan-out-{}.xml'
PCAP_OUT = BASE_DIR + '/OutFiles/xerxes-masscan-pcap-out-{}.pcap'

OUT_DIR = BASE_DIR + '/OutFiles/'
LOG_DIR = BASE_DIR + '/Logs'

TSHARK_BIN = ''

DEBUG_BASE_DIR = os.getcwd()
DEBUG_MASSCAN_BIN = DEBUG_BASE_DIR + '/Scanners/src/masscan/bin/masscan'
DEBUG_MASSCAN_CMD = '-c ' + DEBUG_BASE_DIR + '/Controller/xerxes-masscan.conf -p {} -oX {} --pcap {} {}'
MASSCAN_CONF = DEBUG_BASE_DIR + '/Controller/xerxes-masscan.conf'
DEBUG_XML_OUT = DEBUG_BASE_DIR + '/OutFiles/xerxes-masscan-out-{}.xml'
DEBUG_PCAP_OUT = DEBUG_BASE_DIR + '/OutFiles/xerxes-masscan-pcap-out-{}.pcap'

PORTS = {           20 : 'FTP',
                    21 : 'FTP',
                    22 : 'SSH',
                    23 : 'Telnet',
                    25 : 'SMTP',
                    43 : 'WHOIS',
                    49 : 'TACACS',
                    53 : 'DNS',
                    #67 : 'DHCP/BOOTP (UDP)',
                    #68 : 'DHCP/BOOTP (UDP)',
                    69 : 'TFTP',
                    70 : 'Gopher',
                    79 : 'Finger',
                    80 : 'HTTP',
                    81 : 'HTTP',
                    88 : 'Kerberos',
                    101 : 'Wonderware',
                    102 : 'Microsoft Exchange',
                    110 : 'POP3',
                    111 : 'RPC',
                    119 : 'NNTP',
                    123 : 'NTP',
                    135 : 'Windows RPC',
                    137 : 'NetBIOS',
                    138 : 'NetBIOS',
                    139 : 'SMB',
                    143 : 'IMAP',
                    161 : 'SNMP',
                    179 : 'BGP',
                    201 : 'AppleTalk',
                    389 : 'LDAP',
                    443 : 'HTTPS',
                    445 : 'SMB / Microsoft DS',
                    500 : 'ISAKMP',
                    513 : 'rlogin',
                    514 : 'Syslog',
                    520 : 'RIP',
                    #546 : 'DHCPv6',
                   # 547 : 'DHCPv6',
                    587 : 'SMTP',
                    902 : 'VMWare',
                    1080 : 'SOCKS',
                    1194 : 'OpenVPN',
                    #1337 : 'Leet (Malicious)',
                    1433 : 'MS-SQL',
                    1434 : 'MS-SQL',
                    1521 : 'OracleDB',
                    1629 : 'DameWare',
                    2049 : 'NFS',
                    #2745 : 'Bagle.H (Malicious)',
                    #3127 :'MyDoom (Malicious)',
                    3128 : 'Squid Proxy',
                    3306 : 'MySQL',
                    3389 : 'RDP',
                    5060 : 'SIP',
                    5222 : 'XMPP',
                    5432 : 'Postgres',
                    5666 : 'Nagios',
                    5900 : 'VNC',
                    5901 : 'VNC',
                    5902 : 'VNC',
                    5903 : 'VNC',
                    5904 : 'VNC',
                    5905 : 'VNC',
                    5906 : 'VNC',
                    5907 : 'VNC',
                    5908 : 'VNC',
                    5909 : 'VNC',
                    5910 : 'VNC',
                    6000 : 'X11',
                    #6129 : 'DameWare',
                    #6667 : 'IRC',
                    #9001 : 'TOR/HSQL',
                    #9090 : 'websm',
                    #9091 : 'xmltec-xmlmail',
                    #9100 : 'PDL Data Streaming'
                    #27374 : 'Sub7 (Malicious)'
                    #31337 : 'Back Orifice (Malicious)'
}
#['mysql.auth_plugin', 'mysql.auth_switch_request.data', 'mysql.auth_switch_request.name',
#               'mysql.auth_switch_response.data', 'mysql.error.message', 'mysql.client_auth_plugin', 'mysql.extcaps.server',
#               'mysql.extcaps', 'mysql.extcaps.client', 'mysql.message', 'mysql.parameter', 'mysql.passwd',
#               'mysql.payload', 'mysql.protocol', 'mysql.query', 'mysql.row.text', 'mysql.salt', 'mysql.salt2',
#               'mysql.schema', 'mysql.server_greeting', 'mysql.sqlstate', 'mysql.table_name', 'mysql.user', 'mysql.version']



FIELDS = {
    'data' : ['data.data', 'data.text'],
    'data-text-lines' : ['*'],
    'http' : ['http.accept', 'http.accept_encoding', 'http.accept_language', 'http.authbasic', 'http.authcitrix',
            'http.http.authcitrix.domain', 'http.authcitrix.password', 'http.authcitrix.session', 'http.authcitrix.user',
            'http.authorization', 'http.cache_control', 'http.connection', 'http.content_encoding', 'http.content_type',
            'http.file_data', 'http.host', 'http.location', 'http.proxy_authenticate', 'http.proxy_authorization', 'http.proxy_connect_host',
            'http.proxy_connect_port', 'http.response.code', 'http.response.line', 'http.response.phrase', 'http.server', 'http.ssl_port',
            'http.transfer_encoding', 'http.unknown_header', 'http.www_authenticate', 'http.x_forwarded_for'],
    'http2' : ['http2.altsvc.field_value', 'http2.altsvc.host', 'http2.altsvc.origin', 'http2.altsvc.protocol', 'http2.continuation.header',
            'http2.data.data', 'http2.settings', 'http2.unknown'],
    'isakmp' : ['*'],
    'ftp' : ['ftp.response.code', 'ftp.response.arg'],
    'imap' : ['imap.line', 'imap.response', 'imap.response_tag', 'imap.response.status'],
    'imf' : ['imf.comments', 'imf.content.description', 'imf.content.transfer_encoding', 'imf.ext.authentication_warning',
             'imf.ext.expiry-date', 'imf.ext.mailer', 'imf.ext.mimeole', 'imf.ext.tnef-correlator',
             'imf.ext.uidl', 'imf.ext.virus_scanned', 'imf.extension', 'imf.keywords', 'imf.message_text',
             'imf.siolabel.unknown', 'imf.x400_content_identifier', 'imf.x400_content_type', ],
    'json' : ['json.array', 'json.key', 'json.member', 'json.object', 'json.value.number', 'json.value.string'],
    'jabber' : ['jabber.request', 'jabber.response'],
    'jpeg' : ['jpeg.main_hdr', 'jpeg.payload'],
    'kafka' : ['*'],
    'kerberos' : ['*'],
    'krb4' : ['*'],
    'ldap' : ['*'],
    'mailslot' : ['mailslot.class', 'mailslot.name', 'mailslot.opcode'],
    'messenger' : ['messenger.client', 'messenger.message', 'messenger.server'],
    'mysql' : ['*'],
    'nbdgm' : ['nbdgm.destination_name', 'nbdgm.source_name'],
    'nbss' : ['nbss.called_name', 'nbss.calling_name', 'nbss.continuation_data'],
    'nbns' : ['nbns.data', 'nbns.name'],
    'netbios' : ['netbios.nb_name'],
    'nfs' : ['*'],
    'nfsacl' : ['*'],
    'nfsauth': ['*'],
    'nntp' : ['nntp.response', 'nntp.request'],
    'ntp' : ['*'],
    'ntlmssp' : ['*'],
    'ocsp' : ['*'],
    'openvpn' : ['*'],
    'pgsql' : ['*'],
    'pkcs12' : ['*'],
    'pipe' : ['*'],
    'png' : ['*'],
    'pnp' : ['*'],
    'pnrp' : ['*'],
    'pop' : ['*'],
    'radius' : ['*'],
    'raw_sip' : ['*'],
    'rdm' : ['*'],
    'rdp' : ['*'],
    'rdt' : ['*'],
    'rfr' : ['*'],
    'rlogin' : ['*'],
    'rmp' : ['*'],
    'rpc' : ['*'],
    'rpc_netlogon' : ['*'],
    'rpriv' : ['*'],
    'rsh' : ['*'],
    'rss' : ['*'],
    'sip' : ['*'],
    'smb' : ['*'],
    'smb2': ['*'],
    'smb_netlogon': ['*'],
    'smb_pipe': ['*'],
    'smtp' : ['*'],
    'snmp' : ['*'],
    'socks' : ['*'],
    'ssh' : ['*'],
    'ssl' : ['ssl.record, '],
    'tacacs' : ['*'],
    'tacplus' : ['*'],
    'telnet' : ['*'],
    'tftp' : ['*'],
    'vnc' : ['*'],
    'who' : ['*'],
    'whois' : ['*'],
    'x11' : ['*'],
    'x509af' : ['*'],
    'x509ce': ['*'],
    'x509if': ['*'],
    'x509sat': ['*'],
    'xcap-caps' : ['*'],
    'xcap-error' : ['*'],
    'xmcp' : ['*'],
    'xml' : ['*'],
    'xmpp' : ['*'],

}


ERROR = 1
SUCCESS = 0
