#!/usr/bin/python3
from Xerxes_SQL import *
from xml.dom import minidom
import pymysql
import multiprocessing
import time
import datetime
import socket

def getHostName(IPAddress):
    try:
        name = socket.gethostbyaddr(IPAddress)[0] # function returns a triple, gets the name from first element
    except:
        name = "DNS Resolution Failure"
    return  name

def check_for_CMS(IP_address, file_name):
    return 0


# Function to parse the XML file generated by Masscan and stores the results in the cloud DB
def store_scan_results(file_name):
    db = connect_database()     # connect to the DB via credentials

    xmldoc = minidom.parse(file_name)   # Parse the xml file
    hosts = xmldoc.getElementsByTagName('host') # Gets list of hosts scanned

    # Grabs finish time of the completed scan by Masscan
    scanTimeStr = xmldoc.getElementsByTagName('finished')[0].attributes['timestr'].value

    for host in hosts:
        timeStr = datetime.datetime.fromtimestamp(int(host.attributes['endtime'].value)).strftime('%Y-%m-%d %H:%M:%S')
        portsList = host.getElementsByTagName('port')
        address = host.getElementsByTagName('address')[0].attributes['addr'].value
        region = get_IP_region(db, address)
        returnedName = getHostName(address)
        addressType = host.getElementsByTagName('address')[0].attributes['addrtype'].value
        for port in portsList:
            serviceList = port.getElementsByTagName('service')
            if len(serviceList) == 0:
                insert_into_site_open_services(db, address, port.attributes['portid'].value, "None", "None")
            else:
                for service in serviceList:
                    insert_into_site_open_services(db, address, port.attributes['portid'].value, service.attributes['name'].value, service.attributes['banner'].value)
        insert_site_entry(db, address, returnedName, addressType, region, "Unknown", 0, scanTimeStr)

    db.close()

if __name__ == "__main__":
    file_name = 'xerxes-masscan-out-1.xml'

    store_scan_results(file_name)
    # with open("DatabaseInfo.txt") as f:
    #     content = f.readlines()
    # # you may also want to remove whitespace characters like `\n` at the end of each line
    # content = [x.strip() for x in content]
    #
    # db = pymysql.connect(content[0], content[1], content[2], content[3])